# Generated by Django 5.1.7 on 2025-04-11 11:20

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email пользователя', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Имя пользователя', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь', related_name='customuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Флаг активности пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Фамилия пользователя', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона пользователя', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Права доступа пользователя', related_name='customuser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Имя пользователя, может быть пустым', null=True),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Ферма',
                'verbose_name_plural': 'Фермы',
                'permissions': [('manage_farm', 'Может управлять фермой'), ('add_device', 'Может добавлять устройства'), ('delete_device', 'Может удалять устройства'), ('view_device', 'Может просматривать устройства'), ('control_device', 'Может управлять устройствами')],
            },
        ),
        migrations.CreateModel(
            name='FarmGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.farm', verbose_name='Ферма')),
            ],
            options={
                'verbose_name': 'Группа фермы',
                'verbose_name_plural': 'Группы ферм',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='FarmMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('technician', 'Техник'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farm', verbose_name='Ферма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Членство в ферме',
                'verbose_name_plural': 'Членства в фермах',
                'unique_together': {('user', 'farm')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='farms',
            field=models.ManyToManyField(related_name='members', through='users.FarmMembership', to='users.farm', verbose_name='Фермы'),
        ),
    ]
