# Generated by Django 5.1.7 on 2025-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=91035331, help_text='Имя пользователя, может быть пустым'),
            preserve_default=False,
        ),
    ]
