# Generated by Django 5.1.7 on 2025-04-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=12312312, help_text='Email пользователя', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
