# Generated by Django 5.1.7 on 2025-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Юзернейм, может быть пустым', max_length=10, unique=True),
        ),
    ]
