# Generated by Django 5.1.7 on 2025-04-22 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ExternalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное официальное название организации', max_length=100, unique=True, verbose_name='Название организации')),
                ('type', models.CharField(choices=[('supplier', 'Поставщик'), ('partner', 'Партнер'), ('government', 'Госорганизация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип организации')),
                ('description', models.TextField(blank=True, help_text='Подробное описание деятельности организации', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admins', models.ManyToManyField(help_text='Пользователи с правами администрирования организации', related_name='admin_of_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы')),
            ],
            options={
                'verbose_name': 'Внешняя организация',
                'verbose_name_plural': 'Внешние организации',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Организации, в которых состоит пользователь', related_name='members', to='users.externalorganization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='farm',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Связанная внешняя организация', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='users.externalorganization', verbose_name='Организация'),
        ),
    ]
