# Generated by Django 5.1.7 on 2025-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorganization',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес организации'),
        ),
        migrations.AddField(
            model_name='externalorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail организации'),
        ),
        migrations.AddField(
            model_name='externalorganization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон организации'),
        ),
        migrations.AddField(
            model_name='externalorganization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт организации'),
        ),
    ]
