# Generated by Django 5.1.7 on 2025-04-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_externalorganization_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='externalorganization',
            name='admins',
        ),
        migrations.CreateModel(
            name='ExternalOrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('member', 'Сотрудник'), ('guest', 'Гость')], default='member', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('approved', 'Подтверждено'), ('pending', 'Ожидает подтверждения'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='users.externalorganization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Членство в организации',
                'verbose_name_plural': 'Членства в организациях',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
