# Generated by Django 5.1.7 on 2025-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Организации, в которых состоит пользователь', related_name='members', through='users.ExternalOrganizationMembership', to='users.externalorganization', verbose_name='Организации'),
        ),
    ]
