# Generated by Django 5.1.7 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
