# Generated by Django 5.1.7 on 2025-04-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_device_gateway_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gateway_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_devices', to='dashboard.device'),
        ),
    ]
