# Generated by Django 5.1.7 on 2025-05-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_device_gateway_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('action', models.CharField(blank=True, help_text="Тип действия, например 'open', 'close', 'on', 'off', 'start', 'stop'", max_length=50, null=True, verbose_name='Действие')),
                ('duration', models.DurationField(blank=True, help_text='Длительность действия, если применимо', null=True, verbose_name='Длительность')),
                ('intensity', models.FloatField(blank=True, help_text='Уровень мощности или интенсивности, например, % яркости', null=True, verbose_name='Интенсивность')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Любые дополнительные параметры в формате JSON', verbose_name='Дополнительная информация')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_data', to='dashboard.device', verbose_name='Актуатор')),
            ],
            options={
                'verbose_name': 'Данные актуатора',
                'verbose_name_plural': 'Данные актуаторов',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_a_timesta_a1143d_idx'), models.Index(fields=['actuator'], name='dashboard_a_actuato_17be22_idx')],
            },
        ),
    ]
