# Generated by Django 5.1.7 on 2025-05-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_actuatordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Зона'),
        ),
    ]
